version: '3'

services:

  zoonode1:
      build:
        context: ./zookeeper
        args:
          NODEID: 1
      hostname: zoonode1
      stdin_open: true
      tty: true
      ports:
        - "2181:2181"

  zoonode2:
      build:
        context: ./zookeeper
        args:
          NODEID: 2
      hostname: zoonode2
      stdin_open: true
      tty: true

  zoonode3:
      build:
        context: ./zookeeper
        args:
          NODEID: 3
      hostname: zoonode3
      stdin_open: true
      tty: true


  kafkanode1:
      build:
        context: ./kafka
        args:
          NODEID: 1
          ZOOKEEPER_CONNECT_STRING: zoonode1:2181,zoonode2:2181,zoonode3:2181
      hostname: kafkanode1
      stdin_open: true
      tty: true
      ports:
        - "9092:9092"

  kafkanode2:
      build:
        context: ./kafka
        args:
          NODEID: 2
          ZOOKEEPER_CONNECT_STRING: zoonode1:2181,zoonode2:2181,zoonode3:2181
      hostname: kafkanode2
      stdin_open: true
      tty: true
      ports:
        - "9093:9092"

  kafkanode3:
      build:
        context: ./kafka
        args:
          NODEID: 3
          ZOOKEEPER_CONNECT_STRING: zoonode1:2181,zoonode2:2181,zoonode3:2181
      hostname: kafkanode3
      stdin_open: true
      tty: true
      ports:
        - "9094:9092"